# Generated by Django 2.2.2 on 2019-06-29 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieRoom_ID', models.IntegerField()),
                ('MovieRoom_playing', models.BooleanField()),
                ('MovieRoom_timming', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=64)),
                ('token', models.TextField(max_length=256)),
                ('user_status', models.BooleanField()),
                ('movie_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.MovieRoom')),
            ],
        ),
    ]
