# Generated by Django 2.2.2 on 2019-06-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieroom',
            name='MovieRoom_Name',
            field=models.TextField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
