# Generated by Django 2.2.2 on 2019-06-29 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_movieroom_movieroom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieroom',
            name='MovieRoom_ID',
        ),
    ]
