# Generated by Django 2.2.2 on 2019-07-01 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0004_movieroom_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieuser',
            name='movie_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema_app.MovieRoom'),
        ),
    ]
